### ISSUE TITLE
`pip install sts-lib` 在 Windows 會找不到 sts 命令

### ISSUE THREAD

**Issue by doggy8088** [danny0838/sts-lib#1]
我用以下命令安裝後，似乎在 `C:\Python312\Scripts` 找不到 `sts.exe` 可執行檔？

```sh
pip install sts-lib
```

**Comment by danny0838** [comment]
我測試沒遇到這個問題，可能是您環境的問題？安裝其他 Python 模組正常嗎？

**Comment by danny0838** [comment]
如果還是不行，可試試從原始碼安裝。順帶一提，目前 devel 版本比 master 超前很多，之前因為與 OpenCC 詞庫的問題一直無法很好解決，所以正式版本一直沒上去.......。

**Comment by doggy8088** [comment]
因為你的安裝命令只會安裝到 `C:\Python312\Lib\site-packages\sts` 目錄，在 Windows 並沒有產生 CLI 可執行檔，如果有設定的話，應該會自動產生才對。

因為 Python 我不太熟悉，不知道直接從 Source Code 安裝的步驟是什麼？我只會用 `pip` 安裝套件 😅

**Comment by danny0838** [comment]
Windows 下的 Python 產生可執行檔的路徑有好幾種，和 Python 安裝方式有關，比如從 Windows store 和從 Python 官網安裝，以及用管理員或一般使用者安裝，結果都會不太一樣。還有一些情況下 `pip` 和 `python` 會分屬不同版本（可能是誤安裝多個版本的 Python 導致可執行檔亂掉），那可以改用 `python -m pip ...` 比較能保證和 `python` 一致。

總之我目前測試安裝和執行都是沒有問題，剩下比較偏向 Python 安裝細節的問題，詳細可能要稍微查一下。

如果模組有正常安裝，在命令列輸入 `python -m sts` 應該可以用。如果可執行檔有正常產生，在命令列輸入 `sts` 應該可以用。

從原始碼安裝 Python 模組是指下載原始碼後進入主目錄（有 `setup.*` 的目錄），執行 `pip install .` 即可安裝。

**Comment by doggy8088** [comment]
太棒了，透過 `python -m sts` 確實可以跑！👍
