### ISSUE TITLE
詢問 sts-lib 的演算法邏輯

### ISSUE THREAD

**Issue by doggy8088** [danny0838/sts-lib#2]
接續這一條 Issue 的討論：
https://github.com/BYVoid/OpenCC/issues/852#issuecomment-2041719465

請問是否可以概要說明一下您的演算法邏輯？你現在不是用 mmseg 演算法 (正向最長匹配) 嗎？

**Comment by danny0838** [comment]
還是 mmseg，只是如 https://github.com/BYVoid/OpenCC/issues/475 所述，會先把詞典鏈組合成單一詞典再套用，所以不會有轉換詞庫和分詞詞庫不一致的問題。

**Comment by doggy8088** [comment]
理解了，這樣確實可以解決一些詞彙無法套用的問題。解決方法就是全部寫到分詞表中啊，哈！ XD

**Comment by danny0838** [comment]
難得有人關注，順手把 master 升到 0.20，目前 dictionary 已和 OpenCC 最新版同步，devel 也稍微整理了一下，可自行視需要使用。

後來想到，雖然本程式沒有內建分詞功能，不過其實分析 JSON 輸出即可得知原來的分詞情形。例如在原始碼主目錄下執行：

```cmd
sts convert -c s2twp tests\test_make\join1.in -f json --stdout
```

會輸出：

```json
[[["开"], ["開"]], [["奔", "驰"], ["賓士"]], "上", "路", "\r", "\n", "乙", [["酰"], ["醯"]], [["胆"], ["膽"]], [["碱"], ["鹼"]], "\r", "\n", [["锿"], ["鑀"]], "元", "素"]
```

稍微分析一下即可得知原始輸入文字及實際分詞為：

```
[开][奔驰]上路
乙[酰][胆][碱]
[锿]元素
```
（`[]` 是被詞典比對（及轉換，同時意味著被切出來）的詞，其餘則是未比對到的部分）

另外，本程式產生的合成詞典應該餵給 OpenCC 編譯成 ocd2 就可以使用。（config 輸出要改成 .txt 格式，否則 OpenCC 不認得預設的 .tlist 格式）

**Comment by doggy8088** [comment]
我記錄一下升級的命令:

```sh
pip install --upgrade sts-lib
```

**Comment by danny0838** [comment]
更新到 0.22。修正了一個詞典組合的演算法缺陷，原版本一些不常見的情況下會缺少幾筆可能的待選詞。

另外也升級了 htmlpage 輸出格式，現在應該可以比較正常地做互動式校訂了。

如有興趣研究原始碼，可以參考 [`StsDict.join` 等相關函數](https://github.com/danny0838/sts-lib/blob/master/sts/__init__.py#L430-L525)。

如果有興趣，也可以參考其他幾個專案：
* [千千秀字 - 汉字简繁转换](https://www.qqxiuzi.cn/jfzh/)：有區分簡繁轉換、異體字轉換、地區詞轉換，並且可以互動式修訂，不過看起來沒有開放原始碼。
  這程式的演算法似乎和 OpenCC 類似是切成多個階段處理，因此大概也有類似的分詞bug，還有比如選擇轉台繁時，簡轉繁一對多的選項都無法校訂，看起來就是因為第一階段轉換時若遇到一對多就只取第一輸出，因為含有一對多轉換結果的文本難以再做第二階段轉換。
  目前看起來除了我開發的詞典組合演算法，似乎還未看到有支援多詞典並聯串聯及一對多輸出的解決方案。
* [繁化姬](https://zhconvert.org/)：介面做很漂亮，有很多有趣的功能，但有營利，似乎也沒開放原始碼。

此問題暫時先關閉，如果之後還有發現什麼技術問題可再留言。
