### ISSUE TITLE
字典的想法跟建議

### ISSUE THREAD

**Issue by obxyann** [danny0838/sts-lib#3]
我最近開始閱讀簡體網路小說，我都會先用OpenCC簡轉繁，但結果不如想像的好，有時不如簡單的演算法(無分詞,一階段轉換, 像繁化姬)，唯 OpenCC 是穩定可以大量字數轉換，就研究了一下，發現OpenCC的詞庫STPhrases裡有許多少見詞彙，有的我自己覺得不應該是詞(如"兩個中國" "箇舊" 等等?)，在轉換中除了做分詞這些也是會簡轉繁優先使用，但也出現惱人錯誤...

一个中国  (个中 -> 箇中)
多个旧识  (个旧 -> 箇舊)
入谷人数  (谷人 -> 穀人)
他独斗数名武士   (斗数 -> 斗數)
那面灰蒙蒙的鏡子 (面灰 -> 麪灰)
一块面积不小 (一块面 -> 一塊麪)

我知道解決方式是可以自己增加更多的長詞，但這"分詞理論"比簡化只用關鍵(常見)的一簡轉多繁的詞彙而已不知道會不會更好，我不是專家我不知道...

目前我還是選擇自己加詞去修正我閱讀上發現的錯誤，但我試著增加 MyPhrases.txt 到 OpenCC 的 s2tw.json 不得其門，總有部分沒轉換出來，後來發現你的版本可以正確增加自訂轉換，但 sts 仍著重在演算法上修改，不知你有沒有自用的自訂轉換字典檔，我建議你可以放一版額外的詞庫，我們可以在上面(不改OpenCC的)擴充，大家一起維護，否則STS非自身問題上的轉換錯誤不會比OpenCC少.

他和面孔陌生的男人...和面对的人....轉成 (和面 ->和麪)  他和麵孔陌生的男人...和麵對的人，一般人都是直接使用，就認為 STS 不如別家(都不用自訂修改)吧? ^^

**Comment by danny0838** [comment]
在 [gh-pages 分支](https://github.com/danny0838/sts-lib/tree/gh-pages) 可以看到一些目前修訂過的詞典檔，但目前只是對幾個詞庫做補綴微調，大多也只是確認本套件是否能提供必要的功能，還沒有做更深入的改動，主要是因為還沒決定詞典架構（OpenCC 的架構有一些麻煩的缺點）。

最近正好在和一些簡繁轉換專案的開發者[討論](https://github.com/tongwentang/tongwen-dict/discussions/13#discussioncomment-9131690)能否促成大家共同維護詞典檔，不過目前就詞典/配置檔格式、詞典架構、具體協作方式等方面都還沒有共識，不曉得什麼時候才會有……XD 如果你有興趣，也可以來參與和許願(?)看看。

**Comment by obxyann** [comment]
感謝提修訂詞典檔的訊息，原來這麼多人各自山頭努力，另許願是一定要的，有可以提供綿薄力量的地方也會幫忙 :)
