### ISSUE TITLE
建議字典中新增整行註解的方式

### ISSUE THREAD

**Issue by obxyann** [danny0838/sts-lib#4]
建議字典中新增整行註解的方式

```
//整行註解
//輸入詞1\t轉換詞11\t額外敘述
輸入詞2\t轉換詞21 轉換詞22\t# 註解
```

**Comment by danny0838** [comment]
這個在之前提到的[討論串](https://github.com/tongwentang/tongwen-dict/discussions/13#discussioncomment-9131690)有講到，也許在那邊一起討論會更好？

個人目前不太支持加入整行註解，理由是這個格式主要目的就是希望資料輕巧、簡潔、適合排序和差異比對。一但加了整行註解就不適合排序了。

如果要註解，不如直接改用更規格化的 YAML，有現成的解析程式庫及編輯器工具。

另外，反過來說，如果一定要加入，考量 Unihan、Mediawiki 等專案都用 `#`，我個人是比較支持用 `#` 勝過 `//`。

**Comment by obxyann** [comment]
了解~
